name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: ravarb/devopsrafal
          tag: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ravarb
          password: ${{ secrets.DOCKER }}
